liste2 = []
print(len(liste2))
liste2.append(1)
print(len(liste2))
liste2.insert(0, 2)
print(liste2)
liste3 = liste2.copy()
print(liste3)
liste2.extend(liste3)
print(liste2)
liste2.pop()
print(liste2)
liste2.remove(1)
print(liste2)
