MeineZeichenkette = "   Hallo  welt   "
print(MeineZeichenkette.title())
print(MeineZeichenkette.swapcase())
print(MeineZeichenkette.lstrip())
print(MeineZeichenkette.lower())
print(MeineZeichenkette.join("!*!"))
print(MeineZeichenkette.upper())
print(MeineZeichenkette.strip())
print(MeineZeichenkette.center(22, "*"))
print(MeineZeichenkette.isdigit())
print(MeineZeichenkette.istitle())
print(max(MeineZeichenkette))
print(MeineZeichenkette.split())
print(MeineZeichenkette.split()[0])

